ipfs/benchmarks

.gitignore, runner/config.js, runner/index.js, runner/local.js, runner/package-lock.json, runner/package.json, runner/provision.js, runner/remote.js, runner/test.js
This PR now allows to run tests to run remotely using ssh and your local ~/.ssh/rd_rsa key for auth.
It also provisions that target machine with nvm/node 10 using an ansible playbook under infrastructure.
the runner can be run locally with `STAGE=local LOG_PRETTY=true node runner/index.js`
to run on the remote server configured in config.js use `STAGE=staging LOG_PRETTY=true node runner/index.js`. STAGE should be !== 'local' to run remote.
LOG_PRETTY is to configure pino.
=> Run remote

tests/local-add.js, tests/local-extract.js, tests/package-lock.json, tests/package.json
Tiny PR to remove sinner from tests.
=> Remove spinner from tests

.gitignore, tests/lib/output.js, tests/local-add.js, tests/local-extract.js, tests/package-lock.json, tests/package.json, tests/schema/results.js, tests/unit/output.test.js
Added schema and validation
Added file out
Added unit tests
=> Results schema

tests/lib/output.js, tests/local-add.js, tests/local-extract.js, tests/local-transfer.js, tests/schema/results.js, tests/unit/output.test.js
Formatted results in the file.
Moved the data-grabbing logic to build.
=> pretty-format output

tests/lib/output.js, tests/schema/results.js, tests/unit/output.test.js
Moved validate method to schema/results.
=> move validate to the schema/results

README.md, tests/lib/output.js, tests/package-lock.json, tests/package.json
Added results as table format.
=> Status log

tests/config/index.json, tests/lib/node-factory.js, tests/package-lock.json, tests/package.json
Example to run on the local branch:
REMOTE='true' node local-add
=> Remote run

tests/package.json
The tests now exit although it does take a while.
https://github.com/ipfs/benchmarks/issues/55
=> Changed out dir so data can be removed after tests

README.md, tests/local-add.js, tests/local-extract.js, tests/local-transfer.js, tests/multi-peer-transfer.js, tests/package.json
https://github.com/ipfs/benchmarks/issues/57
Added documentation on running tests against a local js-ipfs branch
=> Doc master branch

README.md, infrastructure/grafana/dashboard.json, runner/README.md, runner/config.js, runner/persistence.js, tests/config/index.json, tests/init-node.js, tests/lib/output.js, tests/lib/runner.js, tests/local-add.js, tests/local-extract.js, tests/local-transfer.js, tests/multi-peer-transfer.js, tests/schema/results.js
Update the results and dashboard schema.
=> Update results and dashboard

infrastructure/playbooks/controller.yaml
=> Ignore fixtures dir on controller

tests/README.md
=> Adds a benchmark tracking table to the tests/README.md

runner/persistence.js
=> Adding ipfs version to db

tests/lib/output.js
File set is now populated again.
=> fix: fix results table

tests/config/index.js, tests/lib/create-node.js, tests/lib/node-factory.js, tests/lib/runner.js, tests/local-add.go.js, tests/package-lock.json, tests/schema/results.js
Add a first go benchmark: local-add
=> Go benchmarks

tests/config/default-config.json, tests/lib/node-factory.js
Disabled peer discovery.
https://github.com/ipfs/benchmarks/issues/82
=> discovery for new peers is disabled

infrastructure/playbooks/benchmarks.yaml
=> fix playbook benchmark script

runner/runner.js, tests/config/index.js, tests/lib/output.js
fix for running local with dashboard
=> fix for running local with dashboard

runner/config.js, runner/runner.js
Local Extract on the dashboard was missing.  Mapped it to correct name.
=> fix local transfer dashboard feed

tests/config/index.js
reduce test file set in config
=> reduce test file set in config

runner/runner.js
quick fix to log test errors and not exit
=> Fix storing points

runner/runner.js
fix for https://github.com/ipfs/benchmarks/issues/117
=> fix: attempt to fix storing undefined ipfs sha

runner/config.js, runner/runner.js
fix for: https://github.com/ipfs/benchmarks/issues/117
=> fix: attempt to fix storing undefnined ipfs sha

infrastructure/playbooks/benchmarks.yaml
fix for https://github.com/ipfs/benchmarks/issues/123
=> fix: attempt to fix the ipfs install script

infrastructure/playbooks/benchmarks.yaml
fix for https://github.com/ipfs/benchmarks/issues/123
=> fix: remove the rm command from script

infrastructure/playbooks/benchmarks.yaml
fix for https://github.com/ipfs/benchmarks/issues/123
=> Fix ipfs install

runner/remote.js
fix for https://github.com/ipfs/benchmarks/issues/128
=> fix remote runner from stopping on error

README.md, tests/config/index.js, tests/lib/runner.js
remove warmup https://github.com/ipfs/benchmarks/issues/79
=> removed warmup flag

tests/init-node.browser.js
fix for https://github.com/ipfs/benchmarks/issues/142
=> fix typo in test

runner/config.js
fix for https://github.com/ipfs/benchmarks/issues/144
=> changed to smaller clinic test files

runner/config.js, tests/README.md, tests/browser/package-lock.json, tests/browser/package.json, tests/browser/src/App.js, tests/browser/src/index.js, tests/config/index.js, tests/init-node.browser.js, tests/local-add.browser.js
Added another browser test to local and remote runner.
=> Browser add file test

runner/config.js, tests/add-multi-kb.browser.js, tests/add-multi-kb.js, tests/browser/src/App.js, tests/config/index.js, tests/lib/fixtures.js
=> Add multi browser test local and remote

README.md, runner/API.md, runner/API_ADD.md, runner/API_DRAIN.md, runner/API_RESTART.md, runner/API_SHOW.md
=> Documentation

runner/config.js, tests/browser/package-lock.json, tests/browser/package.json, tests/browser/src/App.js, tests/config/index.js, tests/peer-transfer.browser.js
Added peer transfer browser test.
=> Add multi browser

runner/API.md, runner/config.js, runner/remote.js
fix attempt for https://github.com/ipfs/benchmarks/issues/169
=> Fix runner

infrastructure/playbooks/controller.yaml
fix for https://github.com/ipfs/benchmarks/issues/174
=> ignore browser/node_modules

infrastructure/playbooks/controller.yaml, tests/config/index.js
adding more files for peer transfer browser test
=> Fix install

README.md, tests/package.json
Fixing some minor things in the instructions.
=> Instruction fixes

tests/test.template
The test template didn't match the current tests anymore.
=> fix: update test template

tests/README.md
Fixed broken link for config file.
=> fix: add new test instruction url

tests/browser/package.json, tests/browser/src/components/peer-transfer.js, tests/browser/src/components/table.js
- fix for peer browser test
- added local dev script
=> fix for peer browser test and adding local dev script

tests/config/index.js, tests/peer-transfer.browser.js
fix for https://github.com/ipfs/benchmarks/issues/186
=> Adding more files for peer transfer

runner/config.js, tests/README.md, tests/add-multi-kb.js, tests/local-add.js
=> Added trickle tests for small multiple files

runner/config.js, tests/config/go-configs.json, tests/config/index.js, tests/extract-js2.go.js
Initial test for https://github.com/ipfs/benchmarks/issues/203
=> Added JS to G0 tests

tests/config/index.js, tests/extract-js2.go.js
Address issue https://github.com/ipfs/benchmarks/issues/203
=> Fix for max buffere error.  Added larger fileset

tests/README.md
In the context of this [review](https://github.com/ipfs/benchmarks/pull/210#pullrequestreview-196558991), I added a step to add new tests.
=> chore: add step for new tests

tests/lib/create-node.js, tests/lib/node-factory.js, tests/lib/runner.js, tests/pubsub-message.js
fix for https://github.com/ipfs/benchmarks/issues/216
=> IPFS options now set in test

runner/compress.js, runner/package-lock.json, runner/package.json, runner/runner.js, runner/test/compress.js, runner/test/queue.js
Compress the extra files that clinic tools generate before we upload to IPFS
=> Compress clinic

README.md, runner/config.js, tests/README.md, tests/config/index.js, tests/lib/create-node.js, tests/lib/node-factory.js, tests/lib/runner.js, tests/local-add.js
Added -s to use trickle or balanced.  Updated readme.
`node local-add -s trickle`
=> Add strategy flag

tests/local-add.js
=> Move logging outside timer

tests/local-extract.js
Updated name to match runner config.
=> updated test name for local extract test

runner/config.js, tests/README.md, tests/config/default-config.json, tests/config/index.js, tests/lib/output.js, tests/multi-peer-transfer.js
=> update name and description based on libp2p options

runner/lib/configBenchmarks.js, tests/README.md, tests/add-multi-kb.js, tests/multi-peer-transfer.js
=> Update addmulit kb test

infrastructure/grafana/dashboard-cpu.json, runner/config.js, runner/persistence.js, tests/schema/results.js
Adding cpu to the dashboard.  https://github.com/ipfs/benchmarks/issues/231
=> Add cpu measurement to db

infrastructure/grafana/dashboard-duration.json, infrastructure/grafana/dashboard-memory.json, runner/config.js, runner/index.js, runner/lib/schema/add.js, runner/persistence.js
Updated the dashboard live and exported the new json files
=> Dasboard nightly

infrastructure/playbooks/roles/redeploy/templates/runner.service.j2
Allows to set ENV vars specific for the runner on the server in /etc/environment
=> read /etc/environment

runner/runner.js
Add `nightly` and `tag` to the API params
=> Extra tags

tests/config/default-config-go.json, tests/config/go-configs.json, tests/extract-go2.js, tests/lib/runner.js, tests/util/create-files.js
issue: https://github.com/ipfs/benchmarks/issues/241
=> attempt to fix js-go tests

tests/README.md
Adding fileset description and utility info to readme.
https://github.com/ipfs/benchmarks/issues/229
=> updating readme with fileset info
